{% set version = "1.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rex
  version: {{ version|replace("-", "_") }}

source:
  fn: rex_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rex_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rex/rex_{{ version }}.tar.gz
  sha256: af42e649c06e4bbdba94d5a1870a7e8347903571c90cd5e5ca40f52307a3bfd6

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-lazyeval
    - r-magrittr
  run:
    - r-base
    - r-lazyeval
    - r-magrittr

test:
  commands:
    - $R -e "library('rex')"           # [not win]
    - "\"%R%\" -e \"library('rex')\""  # [win]

about:
  home: https://github.com/kevinushey/rex
  license: MIT
  license_file: LICENSE
  summary: A friendly interface for the construction of regular expressions.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
