appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: PN8Njoe5FiEJxBzo44c2oQYfd6I+pS7cyl94pi5Tqn7CqHA3J6oc/i9KRIU3mwQzZdno3lZvcH2P+jrm2b6owx+KOodx6Kb6XxysDFPT//IXJ+sUJRb33RiN/JPdGyLdOOUA9jfV1Jy7LjrFIs4UH4GpDsFwvezEChIpp7CHYsNtBcB0MQHmQISAJSaWY8OfKn4bk7IpjN5745ceW2UmZyZTw5I2bJriKOLH3hCfIb201rhTrlZpZ6DsvZ+xg9ix+51Hr5kPqTUQ9zg318ALegQuL+xcR1c270F2MmMUQnzONi5WkmgwS8e/iB5TP47spStqnrIvOh9fNMbNm2GtzmIS946PASqdPJk/HQk6vjbuP6ZOiCuwelflhvJYm32fBrz+83TSt5LLzFHWVdgm/cPQagB6tDLHHkoQGhux7jNo7on+PuXSUysvPJAe9bLkoQRNdF7fCue8OyuCPit8ckz0MK3PtWEgU8Za7BAH1Ui37EkZv1rcpIXsesWHDgdvVNFfJkSigvdD4V6TbBAO6wCeOO33XoWiO/V2PaDjXoDYmY2DJfOHDfJ3hEvxXZ9eSsJcVu5C9s8SgcVaYByaeHRUTuwYV6fPunK+bUkPCmM0CzkSd1gOS18dA0TZZ8B5pXsTujNF2lZgg/0DFDIQkbp4mi1zkABuMG4+9ye0QV4=
conda_forge_output_validation: false
